//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SapRFCService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public string MATNR { get; set; }
        public string MAKTX { get; set; }
        public string ZZCT2 { get; set; }
        public string LIFNR { get; set; }
        public string ZZMATU { get; set; }
        public string ZFVOLUME { get; set; }
        public string ZZPAGE { get; set; }
        public string WGBEZ { get; set; }
        public string ZFPRESERVE_D { get; set; }
        public string ZZSE { get; set; }
        public string NETPR { get; set; }
        public string WAERS { get; set; }
        public string DMBTR { get; set; }
        public Nullable<System.DateTime> ERDAT { get; set; }
        public Nullable<System.DateTime> UDATE { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public int BatchNo { get; set; }
    }
}
